# Generated by Django 5.0.6 on 2024-07-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='попытка'),
        ),
    ]
