# Generated by Django 5.0.6 on 2024-07-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglist',
            options={'verbose_name': 'Список рассылки', 'verbose_name_plural': 'Список рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
    ]
