# Generated by Django 5.0.6 on 2024-07-05 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('status', models.CharField(choices=[('success', 'успешно'), ('failed', 'неудачно')], default='failed', max_length=10, verbose_name='статус попытки')),
                ('response', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='почта')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mailing.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'попытка',
                'verbose_name_plural': 'попытки',
                'ordering': ['-last_time'],
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='messages', serialize=False, to='mailing.message', verbose_name='сообщение')),
                ('client', models.ManyToManyField(related_name='clients', to='mailing.client', verbose_name='клиент')),
                ('mailing', models.ManyToManyField(related_name='mailings', to='mailing.mailing', verbose_name='рассылка')),
            ],
        ),
    ]
