# Generated by Django 4.2.2 on 2024-08-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_client_options_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(related_name='client', to='mailing.client', verbose_name='клиент'),
        ),
    ]
